CREATE TABLE IF NOT EXISTS pacientes (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(200) NOT NULL,
    idade INTEGER NOT NULL,
    sexo VARCHAR(10) NOT NULL,
    peso REAL NOT NULL,
    altura REAL NOT NULL,
    imc REAL NOT NULL,
    passos_diarios INTEGER,
    horas_sono REAL,
    agua_litros REAL,
    calorias INTEGER,
    horas_trabalho INTEGER,
    freq_cardiaca INTEGER,
    pressao_sistolica INTEGER,
    pressao_diastolica INTEGER,
    colesterol INTEGER,
    fumante BOOLEAN DEFAULT FALSE,
    alcool VARCHAR(20),
    historico_familiar BOOLEAN DEFAULT FALSE,
    pratica_atividade BOOLEAN DEFAULT FALSE,
    atividade_vezes_semana INTEGER DEFAULT 0,
    risco_classificado VARCHAR(20),
    probabilidades JSONB,
    data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
